Repository brain-tec/bank-statement-import, pull requests merged in 2020-08, with the labels that each got.

#171 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_txt_xlsx/i18n/zh_CN.po
Labels: 13.0

#173 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_txt_xlsx/i18n/zh_CN.po
Labels: 13.0

#174 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_transfer_move/tests/test_statement.py
Labels: 13.0

#175 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_txt_xlsx/__manifest__.py
Labels: 12.0

#176 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_camt_oca/__manifest__.py
  account_bank_statement_import_camt_oca/models/parser.py
  account_bank_statement_import_transfer_move/tests/test_statement.py
Labels: 13.0

#177 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_txt_xlsx/i18n/zh_CN.po
Labels: 13.0

#178 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/readme/USAGE.rst
  account_bank_statement_import_paypal/static/description/index.html
Labels: 12.0

#179 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__init__.py
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/data/maps.xml
  account_bank_statement_import_paypal/i18n/account_bank_statement_import_paypal.pot
  account_bank_statement_import_paypal/i18n/es.po
  account_bank_statement_import_paypal/models/__init__.py
  account_bank_statement_import_paypal/models/account_bank_statement_import.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_mapping.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
  account_bank_statement_import_paypal/models/account_journal.py
  account_bank_statement_import_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_paypal/readme/HISTORY.rst
  account_bank_statement_import_paypal/readme/USAGE.rst
  account_bank_statement_import_paypal/security/ir.model.access.csv
  account_bank_statement_import_paypal/static/description/icon.png
  account_bank_statement_import_paypal/static/description/index.html
  account_bank_statement_import_paypal/tests/__init__.py
  account_bank_statement_import_paypal/tests/fixtures/activity_en.csv
  account_bank_statement_import_paypal/tests/fixtures/empty_activity.csv
  account_bank_statement_import_paypal/tests/fixtures/statement_en.csv
  account_bank_statement_import_paypal/tests/fixtures/statement_es.csv
  account_bank_statement_import_paypal/tests/test_account_bank_statement_import_paypal.py
  account_bank_statement_import_paypal/views/account_bank_statement_import.xml
  account_bank_statement_import_paypal/views/account_bank_statement_import_paypal_mapping.xml
  account_bank_statement_import_paypal/wizards/__init__.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_paypal/odoo/addons/account_bank_statement_import_paypal
  setup/account_bank_statement_import_paypal/setup.py
Labels: 13.0

#180 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_txt_xlsx/i18n/pt.po
Labels: 12.0

#181 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_paypal/i18n/es.po
Labels: 13.0

#182 Update 20200825 updating from braintec fork for version 13
  account_bank_statement_import_camt_oca/__manifest__.py
  account_bank_statement_import_camt_oca/models/parser.py
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__init__.py
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/data/maps.xml
  account_bank_statement_import_paypal/i18n/account_bank_statement_import_paypal.pot
  account_bank_statement_import_paypal/i18n/es.po
  account_bank_statement_import_paypal/models/__init__.py
  account_bank_statement_import_paypal/models/account_bank_statement_import.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_mapping.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
  account_bank_statement_import_paypal/models/account_journal.py
  account_bank_statement_import_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_paypal/readme/HISTORY.rst
  account_bank_statement_import_paypal/readme/USAGE.rst
  account_bank_statement_import_paypal/security/ir.model.access.csv
  account_bank_statement_import_paypal/static/description/icon.png
  account_bank_statement_import_paypal/static/description/index.html
  account_bank_statement_import_paypal/tests/__init__.py
  account_bank_statement_import_paypal/tests/fixtures/activity_en.csv
  account_bank_statement_import_paypal/tests/fixtures/empty_activity.csv
  account_bank_statement_import_paypal/tests/fixtures/statement_en.csv
  account_bank_statement_import_paypal/tests/fixtures/statement_es.csv
  account_bank_statement_import_paypal/tests/test_account_bank_statement_import_paypal.py
  account_bank_statement_import_paypal/views/account_bank_statement_import.xml
  account_bank_statement_import_paypal/views/account_bank_statement_import_paypal_mapping.xml
  account_bank_statement_import_paypal/wizards/__init__.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.xml
  account_bank_statement_import_transfer_move/tests/test_statement.py
  account_bank_statement_import_txt_xlsx/i18n/zh_CN.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_paypal/odoo/addons/account_bank_statement_import_paypal
  setup/account_bank_statement_import_paypal/setup.py
Labels: 13.0.project_mi_465
