Repository brain-tec/bank-statement-import, pull requests merged in 2020-11, with the labels that each got.

#210 Syncing from upstream OCA/bank-statement-import (13.0)
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0

#211 Syncing from upstream OCA/bank-statement-import (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
Labels: 14.0

#212 Syncing from upstream OCA/bank-statement-import (11.0)
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/static/description/index.html
Labels: 11.0

#213 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/static/description/index.html
Labels: 12.0

#214 Syncing from upstream OCA/bank-statement-import (13.0)
  .pre-commit-config.yaml
  account_bank_statement_import_move_line/README.rst
  account_bank_statement_import_move_line/__init__.py
  account_bank_statement_import_move_line/__manifest__.py
  account_bank_statement_import_move_line/i18n/account_bank_statement_import_move_line.pot
  account_bank_statement_import_move_line/i18n/de.po
  account_bank_statement_import_move_line/i18n/es.po
  account_bank_statement_import_move_line/i18n/fr.po
  account_bank_statement_import_move_line/i18n/hr.po
  account_bank_statement_import_move_line/i18n/nl.po
  account_bank_statement_import_move_line/i18n/pt_BR.po
  account_bank_statement_import_move_line/i18n/pt_PT.po
  account_bank_statement_import_move_line/i18n/sl.po
  account_bank_statement_import_move_line/models/__init__.py
  account_bank_statement_import_move_line/models/account_move_line.py
  account_bank_statement_import_move_line/readme/CONFIGURE.rst
  account_bank_statement_import_move_line/readme/CONTRIBUTORS.rst
  account_bank_statement_import_move_line/readme/DESCRIPTION.rst
  account_bank_statement_import_move_line/readme/USAGE.rst
  account_bank_statement_import_move_line/static/description/icon.png
  account_bank_statement_import_move_line/static/description/index.html
  account_bank_statement_import_move_line/tests/__init__.py
  account_bank_statement_import_move_line/tests/test_account_bank_statement_import_move_line.py
  account_bank_statement_import_move_line/views/account_bank_statement_view.xml
  account_bank_statement_import_move_line/wizards/__init__.py
  account_bank_statement_import_move_line/wizards/account_statement_line_create.py
  account_bank_statement_import_move_line/wizards/account_statement_line_create_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_move_line/odoo/addons/account_bank_statement_import_move_line
  setup/account_bank_statement_import_move_line/setup.py
Labels: 13.0

#216 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_online/README.rst
  account_bank_statement_import_online/__init__.py
  account_bank_statement_import_online/__manifest__.py
  account_bank_statement_import_online/data/account_bank_statement_import_online.xml
  account_bank_statement_import_online/i18n/account_bank_statement_import_online.pot
  account_bank_statement_import_online/migrations/13.0.1.0.0/noupdate_changes.xml
  account_bank_statement_import_online/migrations/13.0.1.0.0/post-migration.py
  account_bank_statement_import_online/models/__init__.py
  account_bank_statement_import_online/models/account_journal.py
  account_bank_statement_import_online/models/online_bank_statement_provider.py
  account_bank_statement_import_online/readme/CONFIGURE.rst
  account_bank_statement_import_online/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online/readme/DESCRIPTION.rst
  account_bank_statement_import_online/readme/USAGE.rst
  account_bank_statement_import_online/security/ir.model.access.csv
  account_bank_statement_import_online/security/online_bank_statement_provider.xml
  account_bank_statement_import_online/static/description/icon.png
  account_bank_statement_import_online/static/description/index.html
  account_bank_statement_import_online/tests/__init__.py
  account_bank_statement_import_online/tests/online_bank_statement_provider_dummy.py
  account_bank_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_bank_statement_import_online/views/account_journal.xml
  account_bank_statement_import_online/views/online_bank_statement_provider.xml
  account_bank_statement_import_online/wizards/__init__.py
  account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online/odoo/addons/account_bank_statement_import_online
  setup/account_bank_statement_import_online/setup.py
Labels: 13.0

#217 Automatically formatting the code according to pre-commit
  account_bank_statement_import_ofx/__manifest__.py
  account_bank_statement_import_ofx/tests/test_import_bank_statement.py
  account_bank_statement_import_ofx/wizard/account_bank_statement_import.py
Labels: 13.0.project_mi_465

#218 Removing unneeded ext folder
  ext/.gitignore
Labels: 13.0.project_mi_465
