Repository brain-tec/bank-statement-import, pull requests merged in 2020-10, with the labels that each got.

#192 Syncing from upstream OCA/bank-statement-import (11.0)
  account_bank_statement_import_online/README.rst
  account_bank_statement_import_online/data/account_bank_statement_import_online.xml
  account_bank_statement_import_online/i18n/account_bank_statement_import_online.pot
  account_bank_statement_import_online/models/account_journal.py
  account_bank_statement_import_online/models/online_bank_statement_provider.py
  account_bank_statement_import_online/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online/readme/DESCRIPTION.rst
  account_bank_statement_import_online/security/online_bank_statement_provider.xml
  account_bank_statement_import_online/static/description/index.html
  account_bank_statement_import_online/tests/online_bank_statement_provider_dummy.py
  account_bank_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_bank_statement_import_online/views/account_journal.xml
  account_bank_statement_import_online/views/online_bank_statement_provider.xml
  account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
  account_bank_statement_import_online_transferwise/README.rst
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
  account_bank_statement_import_online_transferwise/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_transferwise/readme/DESCRIPTION.rst
  account_bank_statement_import_online_transferwise/static/description/index.html
  account_bank_statement_import_online_transferwise/tests/test_account_bank_statement_import_online_transferwise.py
  account_bank_statement_import_online_transferwise/views/online_bank_statement_provider.xml
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/static/description/index.html
Labels: 11.0

#193 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online/README.rst
  account_bank_statement_import_online/data/account_bank_statement_import_online.xml
  account_bank_statement_import_online/i18n/account_bank_statement_import_online.pot
  account_bank_statement_import_online/models/account_journal.py
  account_bank_statement_import_online/models/online_bank_statement_provider.py
  account_bank_statement_import_online/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online/readme/DESCRIPTION.rst
  account_bank_statement_import_online/security/online_bank_statement_provider.xml
  account_bank_statement_import_online/static/description/index.html
  account_bank_statement_import_online/tests/online_bank_statement_provider_dummy.py
  account_bank_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_bank_statement_import_online/views/account_journal.xml
  account_bank_statement_import_online/views/online_bank_statement_provider.xml
  account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
  account_bank_statement_import_online_paypal/README.rst
  account_bank_statement_import_online_paypal/i18n/account_bank_statement_import_online_paypal.pot
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_bank_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_online_paypal/static/description/index.html
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
  account_bank_statement_import_online_paypal/views/online_bank_statement_provider.xml
  account_bank_statement_import_online_transferwise/README.rst
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
  account_bank_statement_import_online_transferwise/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_transferwise/readme/DESCRIPTION.rst
  account_bank_statement_import_online_transferwise/static/description/index.html
  account_bank_statement_import_online_transferwise/tests/test_account_bank_statement_import_online_transferwise.py
  account_bank_statement_import_online_transferwise/views/online_bank_statement_provider.xml
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/static/description/index.html
  account_bank_statement_import_split/README.rst
  account_bank_statement_import_split/models/account_bank_statement_import.py
  account_bank_statement_import_split/readme/CONTRIBUTORS.rst
  account_bank_statement_import_split/readme/DESCRIPTION.rst
  account_bank_statement_import_split/static/description/index.html
  account_bank_statement_import_split/tests/test_account_bank_statement_import_split.py
  account_bank_statement_import_split/views/account_bank_statement_import.xml
  account_bank_statement_import_txt_xlsx/README.rst
  account_bank_statement_import_txt_xlsx/readme/CONTRIBUTORS.rst
  account_bank_statement_import_txt_xlsx/static/description/index.html
Labels: 12.0

#194 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_txt_xlsx/README.rst
  account_bank_statement_import_txt_xlsx/readme/CONTRIBUTORS.rst
  account_bank_statement_import_txt_xlsx/static/description/index.html
Labels: 13.0

#195 Updating from latest OCA 13.0
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/data/maps.xml
  account_bank_statement_import_paypal/models/account_bank_statement_import.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_mapping.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
  account_bank_statement_import_paypal/models/account_journal.py
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/static/description/index.html
  account_bank_statement_import_paypal/tests/test_account_bank_statement_import_paypal.py
  account_bank_statement_import_paypal/views/account_bank_statement_import.xml
  account_bank_statement_import_paypal/views/account_bank_statement_import_paypal_mapping.xml
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.xml
  account_bank_statement_import_txt_xlsx/README.rst
  account_bank_statement_import_txt_xlsx/readme/CONTRIBUTORS.rst
  account_bank_statement_import_txt_xlsx/static/description/index.html
Labels: 13.0.project_mi_465

#196 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_qonto/README.rst
  account_bank_statement_import_online_qonto/__init__.py
  account_bank_statement_import_online_qonto/__manifest__.py
  account_bank_statement_import_online_qonto/i18n/account_bank_statement_import_online_qonto.pot
  account_bank_statement_import_online_qonto/models/__init__.py
  account_bank_statement_import_online_qonto/models/online_bank_statement_provider_qonto.py
  account_bank_statement_import_online_qonto/static/description/icon.png
  account_bank_statement_import_online_qonto/tests/__init__.py
  account_bank_statement_import_online_qonto/tests/test_account_bank_statement_import_online_qonto.py
  account_bank_statement_import_online_qonto/view/online_bank_statement_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online_qonto/odoo/addons/account_bank_statement_import_online_qonto
  setup/account_bank_statement_import_online_qonto/setup.py
Labels: 12.0

#197 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_txt_xlsx/i18n/sk.po
Labels: 12.0

#198 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_txt_xlsx/i18n/sk.po
Labels: 12.0

#200 Syncing from upstream OCA/bank-statement-import (11.0)
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
Labels: 11.0

#201 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
Labels: 12.0

#202 Syncing from upstream OCA/bank-statement-import (11.0)
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
  account_bank_statement_import_online_transferwise/tests/test_account_bank_statement_import_online_transferwise.py
Labels: 11.0

#203 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
  account_bank_statement_import_online_transferwise/tests/test_account_bank_statement_import_online_transferwise.py
Labels: 12.0

#205 Syncing from upstream OCA/bank-statement-import (11.0)
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
Labels: 11.0

#206 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
Labels: 12.0

#207 [t113973] Preparing bank-statement-import for brain-tec's Docker.
  .braintec/deploy.yaml
  ext/.gitignore
Labels: 13.0.project_mi_465

#208 Syncing from upstream OCA/bank-statement-import (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#209 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_ponto/README.rst
  account_bank_statement_import_online_ponto/__init__.py
  account_bank_statement_import_online_ponto/__manifest__.py
  account_bank_statement_import_online_ponto/i18n/account_bank_statement_import_online_ponto.pot
  account_bank_statement_import_online_ponto/models/__init__.py
  account_bank_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_bank_statement_import_online_ponto/readme/CONFIGURE.rst
  account_bank_statement_import_online_ponto/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_ponto/readme/DESCRIPTION.rst
  account_bank_statement_import_online_ponto/readme/USAGE.rst
  account_bank_statement_import_online_ponto/static/description/icon.png
  account_bank_statement_import_online_ponto/static/description/index.html
  account_bank_statement_import_online_ponto/tests/__init__.py
  account_bank_statement_import_online_ponto/tests/test_account_bank_statement_import_online_ponto.py
  account_bank_statement_import_online_ponto/view/online_bank_statement_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online_ponto/odoo/addons/account_bank_statement_import_online_ponto
  setup/account_bank_statement_import_online_ponto/setup.py
Labels: 12.0
