Repository brain-tec/bank-statement-import, pull requests merged in 2021-10, with the labels that each got.

#283 Merging 13.0 into 13.0.project_MI_465
  account_bank_statement_import_online_paypal/README.rst
  account_bank_statement_import_online_paypal/__init__.py
  account_bank_statement_import_online_paypal/__manifest__.py
  account_bank_statement_import_online_paypal/i18n/account_bank_statement_import_online_paypal.pot
  account_bank_statement_import_online_paypal/models/__init__.py
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_bank_statement_import_online_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_online_paypal/readme/ROADMAP.rst
  account_bank_statement_import_online_paypal/readme/USAGE.rst
  account_bank_statement_import_online_paypal/static/description/icon.png
  account_bank_statement_import_online_paypal/static/description/index.html
  account_bank_statement_import_online_paypal/tests/__init__.py
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
  account_bank_statement_import_online_paypal/views/online_bank_statement_provider.xml
  account_bank_statement_import_online_ponto/__manifest__.py
  account_bank_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_bank_statement_import_online_transferwise/README.rst
  account_bank_statement_import_online_transferwise/__init__.py
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/i18n/nl.po
  account_bank_statement_import_online_transferwise/models/__init__.py
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
  account_bank_statement_import_online_transferwise/readme/CONFIGURE.rst
  account_bank_statement_import_online_transferwise/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_transferwise/readme/DESCRIPTION.rst
  account_bank_statement_import_online_transferwise/readme/USAGE.rst
  account_bank_statement_import_online_transferwise/static/description/icon.png
  account_bank_statement_import_online_transferwise/static/description/index.html
  account_bank_statement_import_online_transferwise/tests/__init__.py
  account_bank_statement_import_online_transferwise/tests/test_account_bank_statement_import_online_transferwise.py
  account_bank_statement_import_online_transferwise/views/online_bank_statement_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online_paypal/odoo/addons/account_bank_statement_import_online_paypal
  setup/account_bank_statement_import_online_paypal/setup.py
  setup/account_bank_statement_import_online_transferwise/odoo/addons/account_bank_statement_import_online_transferwise
  setup/account_bank_statement_import_online_transferwise/setup.py
Labels: 13.0.project_mi_465

#284 Syncing from upstream OCA/bank-statement-import (8.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 8.0

#285 Syncing from upstream OCA/bank-statement-import (10.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 10.0

#286 Syncing from upstream OCA/bank-statement-import (11.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 11.0

#288 Syncing from upstream OCA/bank-statement-import (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 13.0

#289 Syncing from upstream OCA/bank-statement-import (14.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 14.0

#292 Syncing from upstream OCA/bank-statement-import (15.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 15.0
