Repository brain-tec/bank-statement-import, pull requests merged in 2021-01, with the labels that each got.

#227 Update project branch 13.0.project_MI_465 with 13.0
  account_bank_statement_import_camt_oca/i18n/nl.po
  account_bank_statement_import_online_ponto/README.rst
  account_bank_statement_import_online_ponto/__init__.py
  account_bank_statement_import_online_ponto/__manifest__.py
  account_bank_statement_import_online_ponto/i18n/account_bank_statement_import_online_ponto.pot
  account_bank_statement_import_online_ponto/models/__init__.py
  account_bank_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_bank_statement_import_online_ponto/readme/CONFIGURE.rst
  account_bank_statement_import_online_ponto/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_ponto/readme/DESCRIPTION.rst
  account_bank_statement_import_online_ponto/readme/USAGE.rst
  account_bank_statement_import_online_ponto/static/description/icon.png
  account_bank_statement_import_online_ponto/static/description/index.html
  account_bank_statement_import_online_ponto/tests/__init__.py
  account_bank_statement_import_online_ponto/tests/test_account_bank_statement_import_online_ponto.py
  account_bank_statement_import_online_ponto/view/online_bank_statement_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online_ponto/odoo/addons/account_bank_statement_import_online_ponto
  setup/account_bank_statement_import_online_ponto/setup.py
Labels: 13.0.project_mi_465

#228 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_camt/README.rst
  account_statement_import_camt/__init__.py
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/i18n/account_statement_import_camt.pot
  account_statement_import_camt/i18n/de.po
  account_statement_import_camt/i18n/es.po
  account_statement_import_camt/i18n/fa.po
  account_statement_import_camt/i18n/fi.po
  account_statement_import_camt/i18n/fr.po
  account_statement_import_camt/i18n/fr_CH.po
  account_statement_import_camt/i18n/gl.po
  account_statement_import_camt/i18n/hr.po
  account_statement_import_camt/i18n/lt_LT.po
  account_statement_import_camt/i18n/nb_NO.po
  account_statement_import_camt/i18n/nl.po
  account_statement_import_camt/i18n/pt_BR.po
  account_statement_import_camt/i18n/pt_PT.po
  account_statement_import_camt/i18n/sl.po
  account_statement_import_camt/models/__init__.py
  account_statement_import_camt/models/account_bank_statement_line.py
  account_statement_import_camt/models/account_journal.py
  account_statement_import_camt/models/account_statement_import.py
  account_statement_import_camt/models/bank_statement.py
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/readme/CONTRIBUTORS.rst
  account_statement_import_camt/readme/DESCRIPTION.rst
  account_statement_import_camt/static/description/icon.png
  account_statement_import_camt/static/description/index.html
  account_statement_import_camt/test_files/golden-camt053-no-ntry.pydata
  account_statement_import_camt/test_files/golden-camt053-txdtls.pydata
  account_statement_import_camt/test_files/golden-camt053.pydata
  account_statement_import_camt/test_files/test-camt053
  account_statement_import_camt/test_files/test-camt053-no-ntry
  account_statement_import_camt/test_files/test-camt053-txdtls
  account_statement_import_camt/test_files/test-camt053.zip
  account_statement_import_camt/tests/__init__.py
  account_statement_import_camt/tests/test_import_bank_statement.py
  account_statement_import_camt/views/account_bank_statement_import.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_statement_import_camt/odoo/addons/account_statement_import_camt
  setup/account_statement_import_camt/setup.py
Labels: 14.0

#229 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_clear_partner/i18n/nl.po
  account_bank_statement_import_camt_oca/i18n/nl.po
  account_bank_statement_import_move_line/i18n/nl.po
  account_bank_statement_import_ofx/i18n/nl.po
  account_bank_statement_import_online/i18n/nl.po
  account_bank_statement_import_txt_xlsx/i18n/nl.po
Labels: 12.0

#230 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_camt_oca/i18n/nl.po
  account_bank_statement_import_move_line/i18n/nl.po
Labels: 13.0

#231 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_camt54/README.rst
  account_statement_import_camt54/__init__.py
  account_statement_import_camt54/__manifest__.py
  account_statement_import_camt54/i18n/account_statement_import_camt54.pot
  account_statement_import_camt54/models/__init__.py
  account_statement_import_camt54/models/account_journal.py
  account_statement_import_camt54/models/account_statement_import.py
  account_statement_import_camt54/models/parser.py
  account_statement_import_camt54/readme/CONTRIBUTORS.rst
  account_statement_import_camt54/readme/CREDITS.rst
  account_statement_import_camt54/readme/DESCRIPTION.rst
  account_statement_import_camt54/static/description/icon.png
  account_statement_import_camt54/static/description/index.html
  account_statement_import_camt54/tests/__init__.py
  account_statement_import_camt54/tests/test_get_partner_ref.py
  account_statement_import_camt54/tests/test_statement.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_statement_import_camt54/odoo/addons/account_statement_import_camt54
  setup/account_statement_import_camt54/setup.py
Labels: 14.0

#232 Update 20210126 - Updating from braintec fork
  account_bank_statement_import_camt_oca/i18n/nl.po
  account_bank_statement_import_move_line/i18n/nl.po
Labels: 13.0.project_mi_465

#233 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_transferwise/i18n/nl.po
Labels: 12.0

#234 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_txt_xlsx/i18n/nl.po
Labels: 13.0
