Repository brain-tec/bank-statement-import, pull requests merged in 2021-04, with the labels that each got.

#251 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/nl.po
Labels: 14.0

#252 Syncing from upstream OCA/bank-statement-import (10.0)
  account_bank_statement_import_move_line/i18n/nl.po
Labels: 10.0

#253 Syncing from upstream OCA/bank-statement-import (11.0)
  account_bank_statement_import_move_line/i18n/nl.po
Labels: 11.0

#254 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_move_line/i18n/nl.po
  account_bank_statement_import_online/i18n/nl.po
Labels: 12.0

#255 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_move_line/i18n/nl.po
  account_bank_statement_import_online/i18n/nl.po
Labels: 13.0

#256 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/nl.po
  account_statement_import_camt/i18n/nl.po
Labels: 14.0

#257 Updating from latest OCA 13.0
  account_bank_statement_import_move_line/i18n/nl.po
  account_bank_statement_import_online/i18n/nl.po
Labels: 13.0.project_mi_465

#258 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/nl.po
Labels: 14.0
