Repository brain-tec/bank-statement-import, pull requests merged in 2021-03, with the labels that each got.

#243 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import/models/account_journal.py
  account_statement_import/views/account_journal.xml
Labels: 14.0

#244 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_txt_xlsx/i18n/fr.po
Labels: 12.0

#246 Updating from latest OCA 13.0
  account_bank_statement_clear_partner/README.rst
  account_bank_statement_clear_partner/__init__.py
  account_bank_statement_clear_partner/__manifest__.py
  account_bank_statement_clear_partner/i18n/account_bank_statement_clear_partner.pot
  account_bank_statement_clear_partner/i18n/nl.po
  account_bank_statement_clear_partner/models/__init__.py
  account_bank_statement_clear_partner/models/account_bank_statement.py
  account_bank_statement_clear_partner/readme/CONFIGURE.rst
  account_bank_statement_clear_partner/readme/CONTRIBUTORS.rst
  account_bank_statement_clear_partner/readme/DESCRIPTION.rst
  account_bank_statement_clear_partner/readme/USAGE.rst
  account_bank_statement_clear_partner/static/description/icon.png
  account_bank_statement_clear_partner/static/description/index.html
  account_bank_statement_clear_partner/tests/__init__.py
  account_bank_statement_clear_partner/tests/test_account_bank_statement_clear_patner.py
  account_bank_statement_clear_partner/views/account_bank_statement_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_clear_partner/odoo/addons/account_bank_statement_clear_partner
  setup/account_bank_statement_clear_partner/setup.py
Labels: 13.0.project_mi_465

#247 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/fr.po
Labels: 14.0

#248 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_ofx/README.rst
  account_statement_import_ofx/__init__.py
  account_statement_import_ofx/__manifest__.py
  account_statement_import_ofx/i18n/account_bank_statement_import_ofx.pot
  account_statement_import_ofx/i18n/account_statement_import_ofx.pot
  account_statement_import_ofx/i18n/de.po
  account_statement_import_ofx/i18n/es.po
  account_statement_import_ofx/i18n/fi.po
  account_statement_import_ofx/i18n/fr.po
  account_statement_import_ofx/i18n/fr_CH.po
  account_statement_import_ofx/i18n/gl.po
  account_statement_import_ofx/i18n/lt_LT.po
  account_statement_import_ofx/i18n/nb_NO.po
  account_statement_import_ofx/i18n/nl.po
  account_statement_import_ofx/i18n/pt_BR.po
  account_statement_import_ofx/i18n/pt_PT.po
  account_statement_import_ofx/i18n/sl.po
  account_statement_import_ofx/models/__init__.py
  account_statement_import_ofx/models/account_journal.py
  account_statement_import_ofx/readme/CONTRIBUTORS.rst
  account_statement_import_ofx/readme/DESCRIPTION.rst
  account_statement_import_ofx/readme/INSTALL.rst
  account_statement_import_ofx/static/description/icon.png
  account_statement_import_ofx/static/description/index.html
  account_statement_import_ofx/tests/__init__.py
  account_statement_import_ofx/tests/test_import_bank_statement.py
  account_statement_import_ofx/tests/test_ofx_file/test_ofx.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_iban.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_wrong.ofx
  account_statement_import_ofx/views/account_statement_import.xml
  account_statement_import_ofx/wizard/__init__.py
  account_statement_import_ofx/wizard/account_statement_import.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_statement_import_ofx/odoo/addons/account_statement_import_ofx
  setup/account_statement_import_ofx/setup.py
Labels: 14.0
