Repository brain-tec/bank-statement-import, pull requests merged in 2021-02, with the labels that each got.

#235 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import/wizard/account_statement_import.py
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/test_files/golden-camt053-txdtls.pydata
  account_statement_import_camt/test_files/golden-camt053.pydata
  account_statement_import_camt/tests/test_import_bank_statement.py
  account_statement_import_camt54/__manifest__.py
  account_statement_import_camt54/models/account_statement_import.py
  account_statement_import_camt54/models/parser.py
  account_statement_import_camt54/tests/test_get_partner_ref.py
  account_statement_import_camt54/tests/test_statement.py
Labels: 14.0

#236 Updating from latest OCA 13.0
  account_bank_statement_import_txt_xlsx/i18n/nl.po
Labels: 13.0.project_mi_465

#237 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import/i18n/es.po
  account_statement_import/models/account_journal.py
  account_statement_import/static/description/icon.png
  account_statement_import/static/description/icon.svg
  account_statement_import/static/description/icon_src.svg
Labels: 14.0

#238 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/fr_BE.po
Labels: 14.0

#239 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_clear_partner/README.rst
  account_bank_statement_clear_partner/__init__.py
  account_bank_statement_clear_partner/__manifest__.py
  account_bank_statement_clear_partner/i18n/account_bank_statement_clear_partner.pot
  account_bank_statement_clear_partner/i18n/nl.po
  account_bank_statement_clear_partner/models/__init__.py
  account_bank_statement_clear_partner/models/account_bank_statement.py
  account_bank_statement_clear_partner/readme/CONFIGURE.rst
  account_bank_statement_clear_partner/readme/CONTRIBUTORS.rst
  account_bank_statement_clear_partner/readme/DESCRIPTION.rst
  account_bank_statement_clear_partner/readme/USAGE.rst
  account_bank_statement_clear_partner/static/description/icon.png
  account_bank_statement_clear_partner/static/description/index.html
  account_bank_statement_clear_partner/tests/__init__.py
  account_bank_statement_clear_partner/tests/test_account_bank_statement_clear_patner.py
  account_bank_statement_clear_partner/views/account_bank_statement_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_clear_partner/odoo/addons/account_bank_statement_clear_partner
  setup/account_bank_statement_clear_partner/setup.py
Labels: 13.0

#240 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import/i18n/fr_BE.po
  account_statement_import/wizard/account_statement_import.py
Labels: 14.0

#241 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/fr_BE.po
Labels: 14.0

#242 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_ponto/i18n/fr_FR.po
Labels: 12.0
