Repository brain-tec/bank-statement-import, pull requests merged in 2021-08, with the labels that each got.

#269 Syncing from upstream OCA/bank-statement-import (8.0)
  README.md
Labels: 8.0

#270 Syncing from upstream OCA/bank-statement-import (10.0)
  README.md
Labels: 10.0

#271 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
Labels: 14.0

#272 Syncing from upstream OCA/bank-statement-import (9.0)
  README.md
Labels: 9.0

#273 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_online_ponto/__manifest__.py
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
Labels: 14.0

#274 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_online/README.rst
  account_statement_import_online/__manifest__.py
  account_statement_import_online/i18n/account_statement_import_online.pot
  account_statement_import_online/i18n/nl.po
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/readme/CONFIGURE.rst
  account_statement_import_online/static/description/index.html
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_statement_import_online/views/online_bank_statement_provider.xml
Labels: 14.0

#275 Update from latest OCA 13.0
  account_bank_statement_import_camt_oca/__manifest__.py
  account_bank_statement_import_camt_oca/models/account_bank_statement_import.py
  account_bank_statement_import_camt_oca/models/parser.py
  account_bank_statement_import_camt_oca/test_files/test-camt053-bookgdt-dttm
  account_bank_statement_import_camt_oca/tests/test_import_bank_statement.py
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
Labels: 13.0.project_mi_465
