Repository brain-tec/bank-statement-import, pull requests merged in 2022-06, with the labels that each got.

#339 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/i18n/account_bank_statement_import_paypal.pot
  account_bank_statement_import_paypal/i18n/es.po
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
Labels: 12.0

#340 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_online_ponto_ing/README.rst
  account_statement_import_online_ponto_ing/__init__.py
  account_statement_import_online_ponto_ing/__manifest__.py
  account_statement_import_online_ponto_ing/i18n/account_statement_import_online_ponto_ing.pot
  account_statement_import_online_ponto_ing/models/__init__.py
  account_statement_import_online_ponto_ing/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto_ing/readme/CONFIGURE.rst
  account_statement_import_online_ponto_ing/readme/CONTRIBUTORS.rst
  account_statement_import_online_ponto_ing/readme/DESCRIPTION.rst
  account_statement_import_online_ponto_ing/static/description/icon.png
  account_statement_import_online_ponto_ing/static/description/index.html
  account_statement_import_online_ponto_ing/tests/__init__.py
  account_statement_import_online_ponto_ing/tests/test_account_statement_import_online_ponto.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_statement_import_online_ponto_ing/odoo/addons/account_statement_import_online_ponto_ing
  setup/account_statement_import_online_ponto_ing/setup.py
Labels: 14.0

#341 Syncing from upstream OCA/bank-statement-import (12.0)
  account_bank_statement_import_online_ponto/__manifest__.py
  account_bank_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
Labels: 12.0

#342 Syncing from upstream OCA/bank-statement-import (13.0)
  README.md
  account_bank_statement_import_split/README.rst
  account_bank_statement_import_split/__init__.py
  account_bank_statement_import_split/__manifest__.py
  account_bank_statement_import_split/i18n/account_bank_statement_import_split.pot
  account_bank_statement_import_split/models/__init__.py
  account_bank_statement_import_split/models/account_bank_statement_import.py
  account_bank_statement_import_split/readme/CONTRIBUTORS.rst
  account_bank_statement_import_split/readme/DESCRIPTION.rst
  account_bank_statement_import_split/static/description/icon.png
  account_bank_statement_import_split/static/description/index.html
  account_bank_statement_import_split/tests/__init__.py
  account_bank_statement_import_split/tests/test_account_bank_statement_import_split.py
  account_bank_statement_import_split/views/account_bank_statement_import.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_split/odoo/addons/account_bank_statement_import_split
  setup/account_bank_statement_import_split/setup.py
Labels: 13.0

#343 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/i18n/account_statement_import_camt.pot
  account_statement_import_camt/i18n/ca.po
  account_statement_import_camt/i18n/de.po
  account_statement_import_camt/i18n/es.po
  account_statement_import_camt/i18n/fa.po
  account_statement_import_camt/i18n/fi.po
  account_statement_import_camt/i18n/fr.po
  account_statement_import_camt/i18n/fr_CH.po
  account_statement_import_camt/i18n/gl.po
  account_statement_import_camt/i18n/hr.po
  account_statement_import_camt/i18n/it.po
  account_statement_import_camt/i18n/lt_LT.po
  account_statement_import_camt/i18n/nb_NO.po
  account_statement_import_camt/i18n/nl.po
  account_statement_import_camt/i18n/pt_BR.po
  account_statement_import_camt/i18n/pt_PT.po
  account_statement_import_camt/i18n/sl.po
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/readme/newsfragment/1_verbose_narration.feature
  account_statement_import_camt/test_files/golden-camt053-txdtls.pydata
  account_statement_import_camt/test_files/golden-camt053.pydata
  account_statement_import_camt/test_files/golden-camt054.pydata
Labels: 14.0

#344 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  account_bank_statement_import_split/README.rst
  account_bank_statement_import_split/__init__.py
  account_bank_statement_import_split/__manifest__.py
  account_bank_statement_import_split/i18n/account_bank_statement_import_split.pot
  account_bank_statement_import_split/models/__init__.py
  account_bank_statement_import_split/models/account_bank_statement_import.py
  account_bank_statement_import_split/readme/CONTRIBUTORS.rst
  account_bank_statement_import_split/readme/DESCRIPTION.rst
  account_bank_statement_import_split/static/description/icon.png
  account_bank_statement_import_split/static/description/index.html
  account_bank_statement_import_split/tests/__init__.py
  account_bank_statement_import_split/tests/test_account_bank_statement_import_split.py
  account_bank_statement_import_split/views/account_bank_statement_import.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_split/odoo/addons/account_bank_statement_import_split
  setup/account_bank_statement_import_split/setup.py
Labels: 13.0.project_mi_465
