Repository brain-tec/bank-statement-import, pull requests merged in 2022-03, with the labels that each got.

#321 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_online/__init__.py
  account_statement_import_online/__manifest__.py
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_statement_import_online/tests/test_account_journal.py
  requirements.txt
Labels: 14.0

#323 Updating from latest OCA 13.0
  account_bank_statement_import_txt_xlsx/i18n/fr.po
Labels: 13.0.project_mi_465

#324 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/sv.po
Labels: 14.0

#326 Syncing from upstream OCA/bank-statement-import (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
Labels: 14.0

#327 Syncing from upstream OCA/bank-statement-import (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0
