Repository brain-tec/bank-statement-import, pull requests merged in 2022-04, with the labels that each got.

#328 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_online/__manifest__.py
  account_bank_statement_import_online/models/account_journal.py
Labels: 13.0

#329 Syncing from upstream OCA/bank-statement-import (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_bank_statement_import_online/__manifest__.py
  account_bank_statement_import_online_paypal/__manifest__.py
  account_bank_statement_import_online_transferwise/__manifest__.py
Labels: 13.0

#330 Updating from latest OCA 13.0
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_bank_statement_import_online/__manifest__.py
  account_bank_statement_import_online/models/account_journal.py
  account_bank_statement_import_online_paypal/__manifest__.py
  account_bank_statement_import_online_transferwise/__manifest__.py
Labels: 13.0.project_mi_465

#331 Syncing from upstream OCA/bank-statement-import (13.0)
  README.md
  account_bank_statement_import_online_qonto/README.rst
  account_bank_statement_import_online_qonto/__init__.py
  account_bank_statement_import_online_qonto/__manifest__.py
  account_bank_statement_import_online_qonto/i18n/account_bank_statement_import_online_qonto.pot
  account_bank_statement_import_online_qonto/models/__init__.py
  account_bank_statement_import_online_qonto/models/online_bank_statement_provider_qonto.py
  account_bank_statement_import_online_qonto/readme/CONFIGURE.rst
  account_bank_statement_import_online_qonto/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_qonto/readme/DESCRIPTION.rst
  account_bank_statement_import_online_qonto/readme/USAGE.rst
  account_bank_statement_import_online_qonto/static/description/icon.png
  account_bank_statement_import_online_qonto/static/description/index.html
  account_bank_statement_import_online_qonto/tests/__init__.py
  account_bank_statement_import_online_qonto/tests/test_account_bank_statement_import_online_qonto.py
  account_bank_statement_import_online_qonto/view/online_bank_statement_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online_qonto/odoo/addons/account_bank_statement_import_online_qonto
  setup/account_bank_statement_import_online_qonto/setup.py
Labels: 13.0

#332 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_camt/README.rst
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/readme/CONTRIBUTORS.rst
  account_statement_import_camt/static/description/index.html
  account_statement_import_camt/test_files/golden-camt054.pydata
  account_statement_import_camt/test_files/test-camt054
  account_statement_import_camt/tests/test_import_bank_statement.py
Labels: 14.0

#333 Updating from latest OCA 13.0
  README.md
  account_bank_statement_import_online_qonto/README.rst
  account_bank_statement_import_online_qonto/__init__.py
  account_bank_statement_import_online_qonto/__manifest__.py
  account_bank_statement_import_online_qonto/i18n/account_bank_statement_import_online_qonto.pot
  account_bank_statement_import_online_qonto/models/__init__.py
  account_bank_statement_import_online_qonto/models/online_bank_statement_provider_qonto.py
  account_bank_statement_import_online_qonto/readme/CONFIGURE.rst
  account_bank_statement_import_online_qonto/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_qonto/readme/DESCRIPTION.rst
  account_bank_statement_import_online_qonto/readme/USAGE.rst
  account_bank_statement_import_online_qonto/static/description/icon.png
  account_bank_statement_import_online_qonto/static/description/index.html
  account_bank_statement_import_online_qonto/tests/__init__.py
  account_bank_statement_import_online_qonto/tests/test_account_bank_statement_import_online_qonto.py
  account_bank_statement_import_online_qonto/view/online_bank_statement_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_import_online_qonto/odoo/addons/account_bank_statement_import_online_qonto
  setup/account_bank_statement_import_online_qonto/setup.py
Labels: 13.0.project_mi_465

#334 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import/demo/partner_bank.xml
Labels: 14.0
