Repository brain-tec/bank-statement-import, pull requests merged in 2022-08, with the labels that each got.

#346 Updating from latest OCA 15.0
  README.md
  account_bank_statement_clear_partner/README.rst
  account_bank_statement_clear_partner/__init__.py
  account_bank_statement_clear_partner/__manifest__.py
  account_bank_statement_clear_partner/i18n/account_bank_statement_clear_partner.pot
  account_bank_statement_clear_partner/i18n/nl.po
  account_bank_statement_clear_partner/models/__init__.py
  account_bank_statement_clear_partner/models/account_bank_statement.py
  account_bank_statement_clear_partner/readme/CONFIGURE.rst
  account_bank_statement_clear_partner/readme/CONTRIBUTORS.rst
  account_bank_statement_clear_partner/readme/DESCRIPTION.rst
  account_bank_statement_clear_partner/readme/USAGE.rst
  account_bank_statement_clear_partner/static/description/icon.png
  account_bank_statement_clear_partner/static/description/index.html
  account_bank_statement_clear_partner/tests/__init__.py
  account_bank_statement_clear_partner/tests/test_account_bank_statement_clear_patner.py
  account_bank_statement_clear_partner/views/account_bank_statement_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_bank_statement_clear_partner/odoo/addons/account_bank_statement_clear_partner
  setup/account_bank_statement_clear_partner/setup.py
Labels: 15.0.project_mi_465

#347 Syncing from upstream OCA/bank-statement-import (12.0)
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_bank_statement_import_ofx/__manifest__.py
  account_bank_statement_import_online/__manifest__.py
  account_bank_statement_import_online_paypal/__manifest__.py
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_save_file/__manifest__.py
  account_bank_statement_import_split/__manifest__.py
  requirements.txt
Labels: 12.0

#348 Syncing from upstream OCA/bank-statement-import (13.0)
  .copier-answers.yml
  .pylintrc
  .pylintrc-mandatory
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
Labels: 13.0

#349 Syncing from upstream OCA/bank-statement-import (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  account_statement_import_online_paypal/tests/test_account_statement_import_online_paypal.py
Labels: 14.0

#350 Syncing from upstream OCA/bank-statement-import (15.0)
  .copier-answers.yml
  .pylintrc
  .pylintrc-mandatory
  README.md
Labels: 15.0

#351 Backmerging 15.0 into 15.0.project_MI_465
  .copier-answers.yml
  .pylintrc
  .pylintrc-mandatory
  README.md
Labels: 15.0.project_mi_465

#352 Backmerging 13.0 into 13.0.project_MI_465
  .copier-answers.yml
  .pylintrc
  .pylintrc-mandatory
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
Labels: 13.0.project_mi_465
