Repository brain-tec/bank-statement-import, pull requests merged in 2022-01, with the labels that each got.

#304 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/README.rst
  account_statement_import/__manifest__.py
  account_statement_import/static/description/index.html
Labels: 14.0

#305 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import/i18n/es_AR.po
  account_statement_import_ofx/i18n/es_AR.po
  account_statement_import_paypal/i18n/es_AR.po
  account_statement_import_txt_xlsx/i18n/es_AR.po
Labels: 14.0

#306 Syncing from upstream OCA/bank-statement-import (13.0)
  account_bank_statement_import_paypal/__manifest__.py
Labels: 13.0

#307 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import/__manifest__.py
  account_statement_import_paypal/i18n/es_AR.po
  account_statement_import_txt_xlsx/i18n/es_AR.po
Labels: 14.0

#308 Merging 13.0 into 13.0.project_MI_465
  account_bank_statement_import_paypal/__manifest__.py
Labels: 13.0.project_mi_465

#309 Syncing from upstream OCA/bank-statement-import (14.0)
  README.md
  account_statement_import_txt_xlsx/__manifest__.py
  account_statement_import_txt_xlsx/migrations/14.0.1.0.0/pre-migrate.py
Labels: 14.0

#310 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/ca.po
  account_statement_import_camt/i18n/ca.po
  account_statement_import_online_ponto/i18n/ca.po
Labels: 14.0
