Repository brain-tec/bank-statement-import, pull requests merged in 2025-04, with the labels that each got.

#624 Syncing from upstream OCA/bank-statement-import (16.0)
  README.md
  account_statement_import_file/README.rst
  account_statement_import_file/__manifest__.py
  account_statement_import_file/static/description/index.html
  account_statement_import_file/wizard/account_statement_import.py
Labels: 16.0

#625 Syncing from upstream OCA/bank-statement-import (17.0)
  account_statement_import_online_stripe/i18n/it.po
Labels: 17.0

#626 Syncing from upstream OCA/bank-statement-import (17.0)
  README.md
  account_statement_import_file/README.rst
  account_statement_import_file/__manifest__.py
  account_statement_import_file/static/description/index.html
  account_statement_import_file/wizard/account_statement_import.py
  account_statement_import_online_stripe/i18n/it.po
Labels: 17.0

#628 Syncing from upstream OCA/bank-statement-import (18.0)
  README.md
  account_statement_import_camt/README.rst
  account_statement_import_camt/__init__.py
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/i18n/account_statement_import_camt.pot
  account_statement_import_camt/i18n/de.po
  account_statement_import_camt/i18n/es.po
  account_statement_import_camt/i18n/fa.po
  account_statement_import_camt/i18n/fi.po
  account_statement_import_camt/i18n/fr.po
  account_statement_import_camt/i18n/fr_CH.po
  account_statement_import_camt/i18n/gl.po
  account_statement_import_camt/i18n/hr.po
  account_statement_import_camt/i18n/it.po
  account_statement_import_camt/i18n/lt_LT.po
  account_statement_import_camt/i18n/nb_NO.po
  account_statement_import_camt/i18n/nl.po
  account_statement_import_camt/i18n/pt_BR.po
  account_statement_import_camt/i18n/pt_PT.po
  account_statement_import_camt/i18n/sl.po
  account_statement_import_camt/models/__init__.py
  account_statement_import_camt/models/account_journal.py
  account_statement_import_camt/models/account_statement_import.py
  account_statement_import_camt/models/account_statement_import_camt_parser.py
  account_statement_import_camt/pyproject.toml
  account_statement_import_camt/readme/CONTRIBUTORS.md
  account_statement_import_camt/readme/CREDITS.md
  account_statement_import_camt/readme/DESCRIPTION.md
  account_statement_import_camt/readme/newsfragment/1_verbose_narration.feature
  account_statement_import_camt/static/description/icon.png
  account_statement_import_camt/static/description/index.html
  account_statement_import_camt/tests/__init__.py
  account_statement_import_camt/tests/samples/golden-camt053-no-ntry.pydata
  account_statement_import_camt/tests/samples/golden-camt053-txdtls.pydata
  account_statement_import_camt/tests/samples/golden-camt053.pydata
  account_statement_import_camt/tests/samples/golden-camt054.pydata
  account_statement_import_camt/tests/samples/test-camt053
  account_statement_import_camt/tests/samples/test-camt053-no-ntry
  account_statement_import_camt/tests/samples/test-camt053-txdtls
  account_statement_import_camt/tests/samples/test-camt053.zip
  account_statement_import_camt/tests/samples/test-camt054
  account_statement_import_camt/tests/test_import_bank_statement.py
  account_statement_import_camt/views/account_bank_statement_import.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#630 Syncing from upstream OCA/bank-statement-import (14.0)
  account_statement_import/i18n/fr.po
Labels: 14.0

#631 Syncing from upstream OCA/bank-statement-import (15.0)
  account_statement_import/i18n/fr.po
Labels: 15.0

#632 Syncing from upstream OCA/bank-statement-import (18.0)
  README.md
  account_statement_import_file/README.rst
  account_statement_import_file/__manifest__.py
  account_statement_import_file/static/description/index.html
  account_statement_import_file/wizard/account_statement_import.py
Labels: 18.0
